/**
 * Cybernews — renders the daily static briefing generated by GitHub Actions.
 * Feed fields are always assigned through textContent; remote HTML is never injected.
 */

document.addEventListener('DOMContentLoaded', () => {
    const page = document.querySelector('.cybernews');
    if (!page) return;

    const elements = {
        template: document.getElementById('news-card-template'),
        featured: document.getElementById('featured-stories'),
        list: document.getElementById('news-list'),
        categories: document.getElementById('category-filters'),
        priorityFilters: document.getElementById('priority-filters'),
        search: document.getElementById('news-search'),
        sort: document.getElementById('news-sort'),
        loadMore: document.getElementById('load-more'),
        clearFilters: document.getElementById('clear-filters'),
        empty: document.getElementById('empty-state'),
        resultCount: document.getElementById('result-count'),
        lastUpdated: document.getElementById('last-updated'),
        sourceStatus: document.getElementById('source-status'),
        sourceSummary: document.getElementById('source-health-summary'),
        sourceList: document.getElementById('source-health-list'),
        threatTape: document.getElementById('threat-tape-text'),
        criticalCount: document.getElementById('critical-count'),
        storyCount: document.getElementById('story-count'),
        healthySources: document.getElementById('healthy-source-count')
    };

    const state = {
        data: null,
        articles: [],
        featuredIds: new Set(),
        category: 'all',
        priority: 'all',
        query: '',
        sort: 'latest',
        visible: 12
    };

    const CATEGORY_LABELS = {
        'all': 'All signals',
        'supply-chain': 'Supply chain',
        'identity': 'Identity',
        'phishing': 'Phishing',
        'ransomware': 'Ransomware',
        'vulnerability': 'Vulnerabilities',
        'malware': 'Malware',
        'cloud': 'Cloud',
        'network': 'Network',
        'endpoint': 'Endpoint',
        'data-breach': 'Data breach',
        'threat-intel': 'Threat intel'
    };

    const PRIORITY_LABELS = {
        critical: 'Critical',
        high: 'High',
        watch: 'Watch',
        context: 'Context'
    };

    function safeHttpUrl(value) {
        try {
            const url = new URL(value);
            return ['http:', 'https:'].includes(url.protocol) ? url.href : '#';
        } catch {
            return '#';
        }
    }

    function dateValue(value) {
        const date = new Date(value);
        return Number.isNaN(date.getTime()) ? new Date(0) : date;
    }

    function formatUpdated(value) {
        return new Intl.DateTimeFormat('en-GB', {
            timeZone: 'Europe/Bucharest',
            day: '2-digit',
            month: 'short',
            hour: '2-digit',
            minute: '2-digit',
            hour12: false
        }).format(dateValue(value));
    }

    function formatStoryTime(value) {
        const date = dateValue(value);
        const hours = Math.max(0, Math.floor((Date.now() - date.getTime()) / 3_600_000));
        if (hours < 1) return 'Just now';
        if (hours < 24) return `${hours}h ago`;
        if (hours < 24 * 7) return `${Math.floor(hours / 24)}d ago`;
        return new Intl.DateTimeFormat('en-GB', {
            day: '2-digit',
            month: 'short'
        }).format(date);
    }

    function signalValue(id, index) {
        let value = 17;
        for (let cursor = 0; cursor < id.length; cursor += 1) {
            value = (value * 31 + id.charCodeAt(cursor) + index * 13) % 997;
        }
        return 18 + (value % 80);
    }

    function renderSignal(container, article, featured) {
        const barCount = featured ? 34 : 24;
        const fragment = document.createDocumentFragment();
        for (let index = 0; index < barCount; index += 1) {
            const bar = document.createElement('span');
            bar.style.setProperty('--signal-height', `${signalValue(article.id, index)}%`);
            bar.style.setProperty('--signal-delay', `${Math.min(index * 16, 320)}ms`);
            fragment.append(bar);
        }
        container.replaceChildren(fragment);
    }

    function appendTag(container, text, isCve = false) {
        const tag = document.createElement('span');
        tag.textContent = text;
        if (isCve) tag.classList.add('is-cve');
        container.append(tag);
    }

    function createCard(article, featured = false) {
        const fragment = elements.template.content.cloneNode(true);
        const card = fragment.querySelector('.news-card');
        card.dataset.priority = article.priority;
        card.dataset.articleId = article.id;
        if (featured) card.dataset.featured = 'true';

        renderSignal(card.querySelector('.news-card__signal'), article, featured);

        const badge = card.querySelector('.priority-badge');
        badge.textContent = `${PRIORITY_LABELS[article.priority] || 'Signal'} · ${article.priority_score}`;

        card.querySelector('.news-card__category').textContent = CATEGORY_LABELS[article.category] || article.category;

        const time = card.querySelector('.news-card__time');
        time.dateTime = article.published_at;
        time.textContent = formatStoryTime(article.published_at);

        card.querySelector('.news-card__title').textContent = article.title;
        card.querySelector('.news-card__summary').textContent = article.summary;
        card.querySelector('.alert-path__why').textContent = article.why_l1_cares;

        const tags = card.querySelector('.news-card__tags');
        (article.cves || []).slice(0, 3).forEach(cve => appendTag(tags, cve, true));
        (article.tags || [])
            .filter(tag => tag !== article.category)
            .slice(0, 4)
            .forEach(tag => appendTag(tags, tag));

        const checks = card.querySelector('.alert-path__checks');
        (article.first_checks || []).forEach(check => {
            const item = document.createElement('li');
            item.textContent = check;
            checks.append(item);
        });

        card.querySelector('.alert-path__escalate').textContent = `Escalate when: ${article.escalate_when}`;
        card.querySelector('.news-card__source').textContent = article.source;

        const link = card.querySelector('.news-card__link');
        link.href = safeHttpUrl(article.url);
        link.setAttribute('aria-label', `Read ${article.title} at ${article.source}`);

        return fragment;
    }

    function selectFeatured(articles) {
        const ordered = [...articles].sort((a, b) =>
            b.priority_score - a.priority_score || dateValue(b.published_at) - dateValue(a.published_at)
        );
        const selected = [];

        for (const article of ordered) {
            if (selected.length >= 3) break;
            if (selected.some(item => item.source === article.source)) continue;
            if (article.is_kev && selected.some(item => item.is_kev)) continue;
            if (selected.length > 1 && selected.some(item => item.category === article.category)) continue;
            selected.push(article);
        }

        for (const article of ordered) {
            if (selected.length >= 3) break;
            if (!selected.some(item => item.id === article.id)) selected.push(article);
        }
        return selected;
    }

    function renderFeatured() {
        const featured = selectFeatured(state.articles);
        state.featuredIds = new Set(featured.map(article => article.id));
        const cards = document.createDocumentFragment();
        featured.forEach(article => cards.append(createCard(article, true)));
        elements.featured.replaceChildren(cards);

        if (featured[0]) {
            elements.threatTape.textContent = `${featured[0].source} · ${featured[0].title}`;
        }
    }

    function categoryCounts() {
        return state.articles.reduce((counts, article) => {
            counts[article.category] = (counts[article.category] || 0) + 1;
            return counts;
        }, {});
    }

    function renderCategoryFilters() {
        const counts = categoryCounts();
        const order = Object.keys(CATEGORY_LABELS).filter(key => key === 'all' || counts[key]);
        const fragment = document.createDocumentFragment();

        order.forEach(category => {
            const button = document.createElement('button');
            const count = category === 'all' ? state.articles.length : counts[category];
            button.type = 'button';
            button.className = `category-chip${state.category === category ? ' active' : ''}`;
            button.dataset.category = category;
            button.setAttribute('aria-pressed', state.category === category ? 'true' : 'false');
            button.append(document.createTextNode(CATEGORY_LABELS[category] || category));
            const number = document.createElement('span');
            number.textContent = count;
            button.append(number);
            fragment.append(button);
        });

        elements.categories.replaceChildren(fragment);
    }

    function searchableText(article) {
        return [
            article.title,
            article.summary,
            article.source,
            article.category,
            ...(article.tags || []),
            ...(article.cves || [])
        ].join(' ').toLowerCase();
    }

    function filteredArticles() {
        const query = state.query.trim().toLowerCase();
        const articles = state.articles.filter(article => {
            const categoryMatch = state.category === 'all' || article.category === state.category;
            const priorityMatch = state.priority === 'all' || article.priority === state.priority;
            const searchMatch = !query || searchableText(article).includes(query);
            return categoryMatch && priorityMatch && searchMatch;
        });

        articles.sort((a, b) => {
            if (state.sort === 'latest') {
                return dateValue(b.published_at) - dateValue(a.published_at);
            }
            return b.priority_score - a.priority_score || dateValue(b.published_at) - dateValue(a.published_at);
        });
        return articles;
    }

    function renderStream() {
        const articles = filteredArticles();
        const visible = articles.slice(0, state.visible);
        const fragment = document.createDocumentFragment();
        visible.forEach(article => fragment.append(createCard(article)));
        elements.list.replaceChildren(fragment);

        elements.resultCount.textContent = `${articles.length} signal${articles.length === 1 ? '' : 's'} shown`;
        elements.empty.hidden = articles.length !== 0;
        elements.loadMore.hidden = state.visible >= articles.length;
        if (!elements.loadMore.hidden) {
            const remaining = articles.length - state.visible;
            elements.loadMore.firstChild.textContent = `Load ${Math.min(12, remaining)} more signals `;
        }
    }

    function renderSourceHealth() {
        const sources = state.data.sources || [];
        const healthy = sources.filter(source => source.status === 'ok').length;
        elements.sourceSummary.textContent = `${healthy}/${sources.length} online`;
        elements.sourceStatus.textContent = `${healthy} of ${sources.length} sources online`;

        const fragment = document.createDocumentFragment();
        sources.forEach(source => {
            const item = document.createElement('li');
            item.textContent = source.name;
            const status = document.createElement('span');
            status.className = 'source-health__state';
            status.textContent = source.status === 'ok' ? 'Online' : 'Unavailable';
            if (source.status !== 'ok') {
                item.classList.add('is-error');
            }
            item.append(status);
            fragment.append(item);
        });
        elements.sourceList.replaceChildren(fragment);
    }

    function renderStats() {
        const stats = state.data.stats || {};
        elements.criticalCount.textContent = stats.critical ?? 0;
        elements.storyCount.textContent = stats.total ?? state.articles.length;
        elements.healthySources.textContent = `${stats.sources_ok ?? 0}/${stats.sources_total ?? 0}`;
        elements.lastUpdated.textContent = formatUpdated(state.data.generated_at);
    }

    function resetVisible() {
        state.visible = 12;
    }

    function setActiveButton(container, selector, value) {
        container.querySelectorAll(selector).forEach(button => {
            const active = button.dataset.priority === value || button.dataset.category === value;
            button.classList.toggle('active', active);
            button.setAttribute('aria-pressed', active ? 'true' : 'false');
        });
    }

    function clearFilters() {
        state.category = 'all';
        state.priority = 'all';
        state.query = '';
        state.sort = 'latest';
        elements.search.value = '';
        elements.sort.value = 'latest';
        setActiveButton(elements.priorityFilters, '[data-priority]', 'all');
        setActiveButton(elements.categories, '[data-category]', 'all');
        resetVisible();
        renderStream();
        elements.search.focus();
    }

    function bindEvents() {
        let searchTimer;
        elements.search.addEventListener('input', event => {
            window.clearTimeout(searchTimer);
            searchTimer = window.setTimeout(() => {
                state.query = event.target.value;
                resetVisible();
                renderStream();
            }, 140);
        });

        elements.sort.addEventListener('change', event => {
            state.sort = event.target.value;
            resetVisible();
            renderStream();
        });

        elements.priorityFilters.addEventListener('click', event => {
            const button = event.target.closest('[data-priority]');
            if (!button) return;
            state.priority = button.dataset.priority;
            setActiveButton(elements.priorityFilters, '[data-priority]', state.priority);
            resetVisible();
            renderStream();
        });

        elements.categories.addEventListener('click', event => {
            const button = event.target.closest('[data-category]');
            if (!button) return;
            state.category = button.dataset.category;
            setActiveButton(elements.categories, '[data-category]', state.category);
            resetVisible();
            renderStream();
        });

        elements.loadMore.addEventListener('click', () => {
            state.visible += 12;
            renderStream();
        });

        elements.clearFilters.addEventListener('click', clearFilters);
    }

    function showLoadError() {
        elements.featured.replaceChildren();
        elements.list.replaceChildren();
        elements.lastUpdated.textContent = 'Briefing unavailable';
        elements.sourceStatus.textContent = 'Could not load the last snapshot';
        elements.resultCount.textContent = 'No data loaded';
        elements.empty.hidden = false;
        elements.empty.querySelector('span').textContent = 'Connection error';
        elements.empty.querySelector('h3').textContent = 'The briefing could not be loaded.';
        elements.empty.querySelector('p').textContent = 'The last snapshot could not be reached. Try again in a moment.';
        elements.clearFilters.textContent = 'Retry briefing';
        elements.clearFilters.addEventListener('click', () => window.location.reload(), { once: true });
    }

    async function loadBriefing() {
        try {
            const dataUrl = new URL('../data/cybernews.json', document.baseURI);
            const response = await fetch(dataUrl, { cache: 'no-cache' });
            if (!response.ok) throw new Error(`HTTP ${response.status}`);
            const data = await response.json();
            if (!Array.isArray(data.articles) || data.articles.length === 0) {
                throw new Error('No stories in briefing');
            }

            state.data = data;
            state.articles = data.articles;
            renderStats();
            renderSourceHealth();
            renderFeatured();
            renderCategoryFilters();
            renderStream();
            bindEvents();
        } catch (error) {
            console.error('Cybernews briefing failed to load:', error);
            showLoadError();
        }
    }

    loadBriefing();
});
